language: java

jdk:
  - oraclejdk8

before_script:
  - git clone https://github.com/yubowenok/sempre
  - cd sempre
  - ../sempreCache.sh
  - ant core corenlp 

# now at flowsense/sempre
script:
  - ../tester.sh
  - rm -rf ../sempre_lib
  - rm -rf ../sempre_fig
  - mv lib ../sempre_lib
  - mv fig ../sempre_fig

cache:
  directories:
  - sempre_lib
  - sempre_fig

