sudo: true

language: java

jdk:
  - oraclejdk8

node_js:
  - "8.11.2"

python:
  - "2.7"

install:
  - yarn install # node dependencies
  - pip install --user -r requirements.txt # wup_server python dependencies
  - git clone https://github.com/yubowenok/sempre
  - cd sempre
  - ../sempreCache.sh
  - ant core corenlp

# now at flowsense/sempre
script:
  - yarn build
  - ../tests/run.sh

before_cache:
  - rm -rf ../sempre_lib
  - rm -rf ../sempre_fig
  - mv lib ../sempre_lib
  - mv fig ../sempre_fig

cache:
  yarn: true
  pip: true
  directories:
    - /home/travis/nltk_data
    - node_modules
    - sempre_lib
    - sempre_fig
